---  
  title: "GGPLOT2 PLOTS"  
author: "Steven Ndung'u"  
date: "`r format(Sys.Date())`"
output:  
  github_document:  
  keep_md: true  
---  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
my_scatterplot <- function(dat, x_c, y_c) {
  scatterpl <- ggplot(dat, aes(x_c, y_c)) + geom_point() +
    geom_abline() +
    ggtitle(label= "") +
    xlab(label= "") +
    ylab(label = "")
  return(scatterpl)
}
my_scatterplot(diamonds, diamonds$x, diamonds$y)
```

```{r}
#Boxplot with a numeric and factor variable


my_boxplot <- function(dat, fill_c, y_c) {
  boxplott <- ggplot(data = dat,mapping = aes(y = y_c, fill = fill_c,x = "")) +
    geom_boxplot() +
    ggtitle(label= "") +
    xlab(label= "") +
    ylab(label = "")
    theme_grey()
  return(boxplott)
}
my_boxplot(diamonds, diamonds$cut, diamonds$y)

```


```{r}

#Boxplot with a numeric and 2 factor variables

my_boxplot <- function(dat, x_c, y_c, fill_c) {
  boxplott <- ggplot(data = dat,mapping = aes(y = y_c, fill = fill_c, x = x_c)) +
    geom_boxplot() +
    ggtitle(label= "") +
    xlab(label= "") +
    ylab(label = "")
    theme_grey()
  return(boxplott)
}
my_boxplot(diamonds, diamonds$cut, diamonds$y, diamonds$color)

```


```{r}

#Barplot of one variable

my_barplot <- function(dat, x_c) {
  barplott <- ggplot(data = dat, mapping = aes(x = x_c)) +
    theme(
      axis.text.x = element_text(
        family = "Times",
        angle = 45,
        colour = "black",
        face = "bold"
      )
    ) +
    theme(
      axis.text.x = element_text(
        colour = "black",
        face = "bold",
        family = "Times",
        angle = 45
      )
    ) +
    geom_bar() + 
    ggtitle(label= "") +
    xlab(label= "") +
    ylab(label = "")
  return(barplott)
}

my_barplot(diamonds, diamonds$cut)


```


```{r}
#Barplot with more than two variables
my_barplot <- function(dat, x_c, fill_c) {
  barplott <- ggplot(data = dat,mapping = aes(x = x_c, fill = fill_c)) +
    theme(
      axis.text.x = element_text(
        family = "Times",
        angle = 45,
        colour = "blue",
        face = "bold"
      )
    ) +
    theme(
      axis.text.x = element_text(
        colour = "blue",
        face = "bold",
        family = "Times",
        angle = 45
      )
    ) +
    geom_bar() + 
    ggtitle(label= "") +
    xlab(label= "") +
    ylab(label = "")
  return(barplott)
}
my_barplot(diamonds, diamonds$cut, diamonds$color)


```


```{r}
#Barplot with one factor and a numeric variable
my_barplot <- function(dat, x_c, y_c) {
  barplott <-
    ggplot(data = dat, mapping = aes(x = x_c, y = y_c)) +
    theme(
      axis.text.x = element_text(
        family = "Times",
        angle = 45,
        colour = "blue",
        face = "bold"
      )
    ) +
    theme(
      axis.text.x = element_text(
        colour = "blue",
        face = "bold",
        family = "Times",
        angle = 45
      )
    ) +
    geom_bar(stat = "identity", position = position_dodge()) +
    ggtitle(label= "") +
    xlab(label= "") +
    ylab(label = "")
  return(barplott)
}
my_barplot(diamonds, diamonds$cut, diamonds$carat)


```


